<?php

namespace AppBundle\Repository;

/**
 * UrlShortenerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UrlShortenerRepository extends \Doctrine\ORM\EntityRepository
{
}
